### ISSUE TITLE
No space between project name and version

### ISSUE THREAD

**Issue by nmatt** [novotnyr/maven-version-idea-plugin#1]
Hi, thank you for this great plugin. I'm having the problem that there is no space between the project name (in bold) and the project version. There is only a space between the project version and the project path. This is under Windows with IntelliJ IDEA 19.1.3 Community Edition (latest current version). Any help or fix would be greatly appreciated.

**Comment by nmatt** [comment]
Looking at your code, I suspect that the tab character ('\t') may be ignored under Windows, and instead a space character must be added.

**Comment by novotnyr** [comment]
Fixed in Release 2

**Comment by nmatt** [comment]
Thanks @novotnyr, I can confirm that the fix works on Windows.
